// icons.js
import {
  FaBeer, FaFacebook, FaTwitter, FaGithub, FaLinkedin, FaInstagram, FaGoogle,
  FaApple, FaAndroid, FaCamera, FaCar, FaBell, FaBook, FaBookmark, FaBuilding,
  FaBus, FaCalculator, FaCalendar, FaCloud, FaCode, FaCoffee, FaCogs, FaComment,
  FaCompass, FaCopy, FaCreditCard, FaDatabase, FaDownload, FaEnvelope, FaEye,
  FaFile, FaFilm, FaFire, FaFlag, FaFolder, FaGamepad, FaGift, FaGlobe, FaHeadphones,
  FaHeart, FaHome, FaImage, FaKey, FaLaptop, FaLightbulb, FaLock, FaMap, FaMicrophone,
  FaMobile, FaMoneyBill, FaMoon, FaMusic, FaPaperPlane, FaPen, FaPhone, FaPlay,
  FaPlus, FaPrint, FaQuestion, FaRecycle, FaRedo, FaRocket, FaRss, FaSave, FaSearch,
  FaServer, FaShare, FaShieldAlt, FaShoppingCart, FaSignInAlt, FaSignOutAlt,
  FaSmile, FaSnowflake, FaStar, FaStickyNote, FaStopwatch, FaSun, FaSync,
  FaTablet, FaTag, FaThumbsUp, FaTimes, FaTools, FaTrash, FaTrophy, FaTruck,
  FaUndo, FaUnlock, FaUpload, FaUser, FaVideo, FaVolumeUp, FaWifi, FaWrench
} from 'react-icons/fa';

const iconList = [
  { name: 'FaBeer', icon: FaBeer },
  { name: 'FaFacebook', icon: FaFacebook },
  { name: 'FaTwitter', icon: FaTwitter },
  { name: 'FaGithub', icon: FaGithub },
  { name: 'FaLinkedin', icon: FaLinkedin },
  { name: 'FaInstagram', icon: FaInstagram },
  { name: 'FaGoogle', icon: FaGoogle },
  { name: 'FaApple', icon: FaApple },
  { name: 'FaAndroid', icon: FaAndroid },
  { name: 'FaCamera', icon: FaCamera },
  { name: 'FaCar', icon: FaCar },
  { name: 'FaBell', icon: FaBell },
  { name: 'FaBook', icon: FaBook },
  { name: 'FaBookmark', icon: FaBookmark },
  { name: 'FaBuilding', icon: FaBuilding },
  { name: 'FaBus', icon: FaBus },
  { name: 'FaCalculator', icon: FaCalculator },
  { name: 'FaCalendar', icon: FaCalendar },
  { name: 'FaCloud', icon: FaCloud },
  { name: 'FaCode', icon: FaCode },
  { name: 'FaCoffee', icon: FaCoffee },
  { name: 'FaCogs', icon: FaCogs },
  { name: 'FaComment', icon: FaComment },
  { name: 'FaCompass', icon: FaCompass },
  { name: 'FaCopy', icon: FaCopy },
  { name: 'FaCreditCard', icon: FaCreditCard },
  { name: 'FaDatabase', icon: FaDatabase },
  { name: 'FaDownload', icon: FaDownload },
  { name: 'FaEnvelope', icon: FaEnvelope },
  { name: 'FaEye', icon: FaEye },
  { name: 'FaFile', icon: FaFile },
  { name: 'FaFilm', icon: FaFilm },
  { name: 'FaFire', icon: FaFire },
  { name: 'FaFlag', icon: FaFlag },
  { name: 'FaFolder', icon: FaFolder },
  { name: 'FaGamepad', icon: FaGamepad },
  { name: 'FaGift', icon: FaGift },
  { name: 'FaGlobe', icon: FaGlobe },
  { name: 'FaHeadphones', icon: FaHeadphones },
  { name: 'FaHeart', icon: FaHeart },
  { name: 'FaHome', icon: FaHome },
  { name: 'FaImage', icon: FaImage },
  { name: 'FaKey', icon: FaKey },
  { name: 'FaLaptop', icon: FaLaptop },
  { name: 'FaLightbulb', icon: FaLightbulb },
  { name: 'FaLock', icon: FaLock },
  { name: 'FaMap', icon: FaMap },
  { name: 'FaMicrophone', icon: FaMicrophone },
  { name: 'FaMobile', icon: FaMobile },
  { name: 'FaMoneyBill', icon: FaMoneyBill },
  { name: 'FaMoon', icon: FaMoon },
  { name: 'FaMusic', icon: FaMusic },
  { name: 'FaPaperPlane', icon: FaPaperPlane },
  { name: 'FaPen', icon: FaPen },
  { name: 'FaPhone', icon: FaPhone },
  { name: 'FaPlay', icon: FaPlay },
  { name: 'FaPlus', icon: FaPlus },
  { name: 'FaPrint', icon: FaPrint },
  { name: 'FaQuestion', icon: FaQuestion },
  { name: 'FaRecycle', icon: FaRecycle },
  { name: 'FaRedo', icon: FaRedo },
  { name: 'FaRocket', icon: FaRocket },
  { name: 'FaRss', icon: FaRss },
  { name: 'FaSave', icon: FaSave },
  { name: 'FaSearch', icon: FaSearch },
  { name: 'FaServer', icon: FaServer },
  { name: 'FaShare', icon: FaShare },
  { name: 'FaShieldAlt', icon: FaShieldAlt },
  { name: 'FaShoppingCart', icon: FaShoppingCart },
  { name: 'FaSignInAlt', icon: FaSignInAlt },
  { name: 'FaSignOutAlt', icon: FaSignOutAlt },
  { name: 'FaSmile', icon: FaSmile },
  { name: 'FaSnowflake', icon: FaSnowflake },
  { name: 'FaStar', icon: FaStar },
  { name: 'FaStickyNote', icon: FaStickyNote },
  { name: 'FaStopwatch', icon: FaStopwatch },
  { name: 'FaSun', icon: FaSun },
  { name: 'FaSync', icon: FaSync },
  { name: 'FaTablet', icon: FaTablet },
  { name: 'FaTag', icon: FaTag },
  { name: 'FaThumbsUp', icon: FaThumbsUp },
  { name: 'FaTimes', icon: FaTimes },
  { name: 'FaTools', icon: FaTools },
  { name: 'FaTrash', icon: FaTrash },
  { name: 'FaTrophy', icon: FaTrophy },
  { name: 'FaTruck', icon: FaTruck },
  { name: 'FaUndo', icon: FaUndo },
  { name: 'FaUnlock', icon: FaUnlock },
  { name: 'FaUpload', icon: FaUpload },
  { name: 'FaUser', icon: FaUser },
  { name: 'FaVideo', icon: FaVideo },
  { name: 'FaVolumeUp', icon: FaVolumeUp },
  { name: 'FaWifi', icon: FaWifi },
  { name: 'FaWrench', icon: FaWrench },
];


export default iconList;